LFUserBundle_Edition_new:
    pattern:  /user/new/{country}
    defaults: { _controller: LFUserBundle:Edition:new }
    requirements:
        culture:  fr|es|ch

LFUserBundle_Show_list:
    pattern:  /user/list
    defaults: { _controller: LFUserBundle:Show:list }
    
login:
    pattern: /login
    defaults: { _controller: LFUserBundle:Security:login }
    
login_check:
    pattern: /login_check
    
logout:
    pattern: /logout